site_name: My Portfoliio
site_author: Marek Kasiarz
site_description: >-
    Clear Insights • Reproducible ML • Practical AI Agents

site_url: https://edutroniks.github.io/ds_ai_portfolio/

markdown_extensions:
  - attr_list
  - toc:
      permalink: true

theme:
  name: material
  features:           # Musi być dokładnie pod 'name'
    - toc.follow
    - navigation.top

nav:
  - Home: index.md
  - Projects:
      - Iris Project: iris/index.md
      - HM Predictor App: hm/index.md
  - About Me: about.md
